#docker-compose.yaml
version: '3'
services:
  demo-app:
    build:
      context: . # 현재 디렉토리를 빌드 컨텍스트로 사용
    volumes:
      - .dockervenv:/src/.venv
      - .:/src # 현재 디렉토리를 컨테이너의 /src 디렉토리에 마운트
    ports:
      - 8000:8000 #호스트 머신의 8000번 포트를 docker의 8000번 포트와 연결
    environment:
      - WATCHFILES_FORCE_POLLING=true